<?php
/* @var \Sga\MediaGallery\Block\Adminhtml\Gallery $block */
?>
<div class="media-gallery">
    <label class="open" title="<?= __('Open Media Gallery') ?>"></label>
    <script>
        require([
            'jquery',
            'mage/adminhtml/browser'
        ], function ($, browser) {
            $(document).on('click', '.media-gallery .open', function () {
                var openDialogUrl = '<?= $block->getUrl('cms/wysiwyg_images/index') ?>' +
                    '/target_element_id/1/' +
                    '/store/0' +
                    '/?isAjax=true';

                openDialogUrl += '&current_tree_path=' + Base64.idEncode('/');

                browser.openDialog(openDialogUrl);
            });
        });
    </script>
</div>
